name: .NET 8 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore MathUtil.sln

    - name: Build solution
      run: dotnet build MathUtil.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test TestExponentialFunction/TestExponentialFunction.csproj --configuration Release --no-restore --verbosity normal
